### ISSUE TITLE
I cannot resume the training of model.

### ISSUE THREAD

**Issue by wannaphong** [meanna/ThaiLMCUT#2]
Hello. I cannot resume the training of your model. (Tokenizer_2019-11-11_04.24.19.pth)

`!python Tokenizer.py --load_from Tokenizer_2019-11-11_04.24.19 --epoch 5  --learning_rate 0.0005 --dataset best --over_write 1 --save_to newbest`
```
resume training the tokenizer...Tokenizer_2019-11-11_04.24.19
overwrite the weights to  Tokenizer_2019-11-11_04.24.19
get the network structure from the loaded model...

Namespace(adam_lr_decay=0.0, add_note='load from Tokenizer_2019-11-11_04.24.19 , lst20 , lr 0.0005, epoch 5', batchSize=64, char_dropout_prob=0.01, char_embedding_size=200, clip_grad=0.5, dataset='best', epoch=5, hidden_dim=514, layer_num=2, learning_rate=0.0005, len_lines_per_chunk=1000, load_from='Tokenizer_2019-11-11_04.24.19', lr_decay=0.01, lstm_num_direction=2, optim='adam', over_write=1, printPrediction=0, save_model=1, save_to='newbest', sequence_length=150, sgd_momentum=0.02)

model name:  Tokenizer_2019-11-11_04.24.19
GPU:  False

 start training...
Traceback (most recent call last):
  File "Tokenizer.py", line 324, in <module>
    model = Model(bi_lstm)
  File "Tokenizer.py", line 180, in __init__
    module.load_state_dict(checkpoint[name], strict=True)
  File "/usr/local/lib/python3.6/dist-packages/torch/nn/modules/module.py", line 847, in load_state_dict
    self.__class__.__name__, "\n\t".join(error_msgs)))
RuntimeError: Error(s) in loading state_dict for Embedding:
	size mismatch for weight: copying a param with shape torch.Size([76, 200]) from checkpoint, the shape in current model is torch.Size([181, 200]).
```

**Comment by meanna** [comment]
Hello @wannaphong , 

In `train/data_util.py`, replace  `CHARS` with
`CHARS = " กขฃคฅฆงจฉชซฌญฐฎฏฐฑฒณดตถทธนบปผฝพฟภมยรฤลฦวศษสหฬอฮฯะัาำิีึืุูเแโใไๅๆ็่้๊๋์ํ"`

The weight `Tokenizer_2019-11-11_04.24.19.pth` is trained on a GPU using this character set. 
I saw you trained the model on a CPU. I'm afraid you can only resume the model on a GPU device.

Hope it works

Suteera

**Comment by meanna** [comment]
If you get the error message 
```  File "Tokenizer.py", line 211, in forward_cl
    loss = classifier_loss(logits.view(-1, 2), target_tensor.view(-1))
RuntimeError: view size is not compatible with input tensor's size and stride (a
t least one dimension spans across two contiguous subspaces). Use .reshape(...) 
instead.
```

In `train/Tokenizer` replace line 211 and 212 with

```
loss = classifier_loss(logits.reshape(-1, 2), target_tensor.reshape(-1))
return loss, target_tensor.reshape(-1).size()[0], log_probs, input_tensor, target_tensor

```

**Comment by wannaphong** [comment]
@meanna Thank you. 👍
